MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG_CNN_M_1024.VGG_CNN_M_1024_conv5_body
  NUM_CLASSES: 3 # car, van + background
  FASTER_RCNN: True
  BACKBONE_TYPE: 'CNN_M_1024'
  PRETRAINED_BACKBONE_WEIGHTS: ''
  PRETRAINED_DETECTRON_WEIGHTS: ''
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0005 # originally 0.0001 for COCO
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 15000
  STEPS: [0, 9000, 12000]
RPN:
  SIZES: (16, 32, 64, 128, 256)
FAST_RCNN:
  ROI_BOX_HEAD: VGG_CNN_M_1024.VGG_CNN_M_1024_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  DATASETS: ('vkitti_clone_trainval',)
  PROPOSAL_FILES: ('data/proposals/vkitti_clone_trainval/rpn_proposals.pkl',)
  SCALES: (370,)
  MAX_SIZE: 1242
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  SNAPSHOT_ITERS: 20000
  USE_FLIPPED: False
TEST:
  DATASETS: ('vkitti_clone_test',)
  PROPOSAL_FILES: ('data/proposals/vkitti_clone_test/rpn_proposals.pkl',)
  SCALE: 370
  MAX_SIZE: 1242
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: . # insert path in run command
CUSTOM_DATA:
  FORCE_TEST: True
  FORCE_JSON_DATASET_EVAL: True
# options specifically for Perceptual GAN version
GAN:
  GAN_MODE_ON: True
  AREA_THRESHOLD: 60
  MODEL:
    CONV_BODY_FC_HEAD: VGG_CNN_M_1024.VGG_CNN_M_1024_fc_head
    LABEL_SMOOTHING: 0.9
  TRAIN:
    DATASETS_REAL: ('vkitti_clone_trainval',)
    PROPOSAL_FILES_REAL: ('data/proposals/vkitti_clone_trainval/rpn_proposals.pkl',)
    DATASETS_FAKE: ('vkitti_rain_trainval',)
    PROPOSAL_FILES_FAKE: ('data/proposals/vkitti_rain_trainval/rpn_proposals.pkl',)
    TRANSFER_LEARNING: True
    IMS_PER_BATCH_PRE: 1
    BATCH_SIZE_PER_IM_PRE: 128
    FG_FRACTION_PRE: 0.25
    IMS_PER_BATCH_D: 2
    BATCH_SIZE_PER_IM_D: 8
    FG_FRACTION_D: 1.0
    IMS_PER_BATCH_G: 2
    BATCH_SIZE_PER_IM_G: 64
    FG_FRACTION_G: 0.25
    SNAPSHOT_ITERS: 5000
  SOLVER:
    TYPE_G: 'SGD'
    TYPE_D: 'SGD'
    WEIGHT_DECAY_D: 0.0005
    WEIGHT_DECAY_G: 0.0005
    LR_POLICY_G: steps_with_decay
    LR_POLICY_D: steps_with_decay
    BASE_LR_D: 0.0002 #0.0001
    BASE_LR_G: 0.0002 #0.0001
    GAMMA_D: 0.1
    GAMMA_G: 0.1
    MAX_ITER: 8000 #16000 # 24000 - 8000
    STEPS: [0, 6000] #[0, 12000]
    WARM_UP_ITERS: 500
    PRE_ITER: 15000 #30000
    PRE_WARM_UP_ITERS: 500
    STEPS_PRE: [0, 9000, 12000] #[0, 18000, 24000] #[0, 9000, 12000]