MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG_CNN_M_1024.VGG_CNN_M_1024_conv5_body
  NUM_CLASSES: 46
  FASTER_RCNN: True
  BACKBONE_TYPE: 'CNN_M_1024'
  PRETRAINED_BACKBONE_WEIGHTS: ''
  PRETRAINED_DETECTRON_WEIGHTS: ''
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0005 # originally 0.0001 for COCO
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 1000
  STEPS: [0, 545, 810]
RPN:
  SIZES: (16, 32, 64, 128, 256)
FAST_RCNN:
  ROI_BOX_HEAD: VGG_CNN_M_1024.VGG_CNN_M_1024_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  DATASETS: ('tt100k_trainval_ignore_complete_overfit',)
  SCALES: (1600,)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  SNAPSHOT_ITERS: 300
  USE_FLIPPED: False
TEST:
  DATASETS: ('tt100k_test_ignore_complete_overfit',)
  SCALE: 1600
  MAX_SIZE: 1600
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: . # insert path in run command
CUSTOM_DATA:
  FORCE_TEST: True
  FORCE_JSON_DATASET_EVAL: True
GAN:
  TRAIN:
    DATASETS_SOURCE: ('tt100k_trainval_ignore_complete_overfit',)