MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG_CNN_M_1024.VGG_CNN_M_1024_conv5_body
  NUM_CLASSES: 3 # car, van + background
  FASTER_RCNN: True
  RPN_ONLY: True # for RPN proposal file generation
  BACKBONE_TYPE: 'CNN_M_1024'
  PRETRAINED_BACKBONE_WEIGHTS: ''
  PRETRAINED_DETECTRON_WEIGHTS: ''
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005 # originally 0.0001 for COCO
  LR_POLICY: steps_with_decay
  BASE_LR: 0.00125 #0.0025
  GAMMA: 0.1
  MAX_ITER: 30000 #15000
  STEPS: [0, 18000, 24000] #[0, 9000, 12000]
RPN:
  SIZES: (16, 32, 64, 128, 256)
FAST_RCNN:
  ROI_BOX_HEAD: VGG_CNN_M_1024.VGG_CNN_M_1024_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  DATASETS: ('vkitti_clone_trainval',)
  SCALES: (370,)
  MAX_SIZE: 1242
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  SNAPSHOT_ITERS: 6600
  USE_FLIPPED: False
TEST:
  DATASETS: ('vkitti_rain_test', 'vkitti_rain_trainval', 'vkitti_fog_test', 'vkitti_fog_trainval', 'kitti_test_ignore_complete', 'kitti_trainval_ignore_complete')
  SCALE: 370
  MAX_SIZE: 1242
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: . # insert path in run command
CUSTOM_DATA:
  FORCE_TEST: True
  FORCE_JSON_DATASET_EVAL: True
# options specifically for Perceptual GAN version
GAN:
  GAN_MODE_ON: False
